// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

import (
	"easygo/internal/controller"
	"easygo/internal/dao"
	"easygo/internal/model"
	"easygo/internal/router"
	"easygo/pkg/jwt"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, err := InitGorm()
	if err != nil {
		return nil, nil, err
	}
	userDao := &dao.UserDao{
		DB: db,
	}
	client, err := InitRedis()
	if err != nil {
		return nil, nil, err
	}
	jwtJwt := &jwt.Jwt{
		Redis: client,
	}
	userModel := &model.UserModel{
		UserDao: userDao,
		Jwt:     jwtJwt,
	}
	user := &controller.User{
		UserModel: userModel,
	}
	test := &controller.Test{
		RedisTest: client,
	}
	routerRouter := &router.Router{
		UserAPI: user,
		TestAPI: test,
		Jwt:     jwtJwt,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
	}, nil
}
