// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package internal

import (
	controller2 "easygo/internal/controller"
	dao2 "easygo/internal/dao"
	model2 "easygo/internal/model"
	router2 "easygo/internal/router"
	"easygo/pkg/jwt"
)

// Injectors from wire.go:

func BuildInjector() (*Injector, func(), error) {
	db, err := InitGorm()
	if err != nil {
		return nil, nil, err
	}
	userDao := &dao2.UserDao{
		DB: db,
	}
	client, err := InitRedis()
	if err != nil {
		return nil, nil, err
	}
	jwtJwt := &jwt.Jwt{
		Redis: client,
	}
	userModel := &model2.UserModel{
		UserDao: userDao,
		Jwt:     jwtJwt,
	}
	user := &controller2.User{
		UserModel: userModel,
	}
	test := &controller2.Test{
		RedisTest: client,
	}
	routerRouter := &router2.Router{
		UserAPI: user,
		TestAPI: test,
		Jwt:     jwtJwt,
	}
	engine := InitGinEngine(routerRouter)
	injector := &Injector{
		Engine: engine,
	}
	return injector, func() {
	}, nil
}
